version: "3.3"

services:
    neo_boa:
        build: ./neo-boa
        volumes:
            - ./smartcontract:/python-contracts
            - compiled_contracts:/compiled-contracts

    private_net:
        image: cityofzion/neo-privatenet

    redis:
        image: redis:3.0-alpine
        restart: always

    neo_python:
        build: ./neo-python
        depends_on:
            - neo_boa
        volumes:
            - compiled_contracts:/neo-python/contracts
            - private_chain:/neo-python/Chains/privnet
        links:
            - private_net
        stdin_open: true
        tty: true

    middleware:
        build: ./middleware
        links:
            - redis
        env_file:
            - ./secrets.env

volumes:
    private_chain:
    compiled_contracts:
