version: "3.3"

services:
    neo_boa:
        build: ./neo-boa
        volumes:
            - ./smartcontract:/python-contracts
            - compiled_contracts:/compiled-contracts

    private_net:
        image: cityofzion/neo-privatenet

    neo_python:
        build: ./neo-python
        depends_on:
            - neo_boa
        volumes:
            - wallets:/neo-python/wallets
            - compiled_contracts:/neo-python/contracts
        links:
            - private_net
        stdin_open: true
        tty: true

    middleware:
        build: ./middleware
        volumes:
            - wallets:/neo-python/wallets/neo-privnet.wallet

volumes:
    wallets:
    compiled_contracts:
